config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
      # 商品編集の際に画像を削除した際、動くメソッドを定義
      delete 'image_delete', defoults: {format: 'json'}
    end
  end
  
  resources :users, only: [:show, :new] do
    collection do
      get :sms
      get :sms_input
      get :completed
    end
    # member do
    #   get "/credit_cards/:id/new" => "credit_card#new"
    # end
  end
  
  resources :purchases, only: [:show] do
    member do
      get :verification_address
      post :create
      post "/credit_cards/:id/create" => "credit_card#create"
      get "pay", to: "purchases#pay"
      post "buy", to: "purchases#buy"
    end
  end
  resources :credit_cards, only: [:index, :new, :create] do
    member do
      # get :new
      # post :create
      post "delete", to: "credit_cards#delete"
    end
  end

  root "items#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"
  # before_action :set_item, only: [:new, :create]
  before_action :set_card

  def index #CardのデータをPayjpに送って情報を取り出す
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"] #初期化です。
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)
      # ブランドアイコンを表示するためのコードです。
      @card_brand = @card_information.brand
      
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "SaisonCard"
        @card_src = "saison-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end

  def new     # カードの登録画面。送信ボタンを押すとcreateアクションへ。
    @card = CreditCard.where(user_id: current_user.id).first
    # redirect_to pay_purchase_path(@item.id) if @card.present?
  end

   def create     # PayjpとCardのデータベースを作成
    @address = Address.new
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

    if params["payjp_token"].blank?
      redirect_to new_credit_card_path
      # redirect_to credit_card_path
    else
      # トークンが正常に発行されていたら、顧客情報をPAY.JPに登録します。
      customer = Payjp::Customer.create(
        card: params["payjp_token"]     # 直前のnewアクションで発行され、送られてくるトークンをここで顧客に紐付けて永久保存します。
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to root_path
      else
        redirect_to root_path
      end
    end
  end

  def delete     # PayjpとCardのデータベースを削除します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    if @card.delete
      redirect_to credit_cards_path(current_user)
    else
      redirect_to root_path(current_user)
    end
  end

  private

  # def set_item
  #   @item = Item.find(params[:id])
  #   @images = @item.product_images
  #   @image = @images.first 
  # end

  def set_card
    @card = CreditCard.where(user_id: current_user.id).first if CreditCard.where(user_id: current_user.id).present?
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_add_card.html.haml
.credit-card-add_card-wrapper
  .credit-content
    .credit-content__item
      %h2.credit-content__item__title
        支払い方法
      .payment__main
        .payment__list
          .payment__list__content
            %h3.sub__head クレジットカード一覧
        .add__card
          .payment__list__content
            -# = link_to credit_card_path(current_user.id), class: "red__btn" do
            = link_to new_credit_card_path(current_user), class: "red__btn" do
              %i
              = icon('fas', 'credit-card', class: "card__icon")
              クレジットカードを追加する
        .how__not__regist
          = link_to user_path(current_user) do
            戻る
          = link_to "支払い方法について" 

app/views/credit_cards/add_card.html.haml
.credit-card-add_card-wrapper
  .verification_header
    = render partial: 'items/shared/verification_header'
  .credit-content
    .credit-content__item
      %h2.credit-content__item__title
        支払い方法
      .payment__main
        .payment__list
          .payment__list__content
            %h3.sub__head クレジットカード一覧
        .add__card
          .payment__list__content
            = link_to new_credit_card_path, class: "red__btn" do
              %i
              = icon('fas', 'credit-card', class: "card__icon")
              クレジットカードを追加する
        .how__not__regist
          = link_to "支払い方法について" 
  .verification_footer
    = render partial: 'items/shared/verification_footer'

app/views/credit_cards/index.html.haml
.credit-card-show-wrapper
  .verification_header
    = render partial: 'items/shared/verification_header'
  - if @card.present?
    .credit-content
      .credit-content__item
        %h2.credit-content__item__title
          支払い方法
        .payment__main
          .payment__list
            .payment__list__content
              %h3.sub__head クレジットカード一覧
          .card__payment__list
            %form.card__payment__content
            .card__list
              .card__list__picture
                -# = @card_brand
                -# = image_tag "assets/#{@card_src}", width: '26', height: '20', alt: @card_brand, id: "card_image"
                = image_tag "#{@card_src}", width: '50', height: '30', alt: @card_brand
            .card__number 
              = "**** **** **** " + @card_information.last4
            .expire__date 
              - exp_month = @card_information.exp_month.to_s
              - exp_year = @card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
            = form_tag(delete_credit_card_path(@card.id), method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button.delete__button 削除する
          .how__not__regist
            = link_to user_path(current_user) do
              戻る
            = link_to "支払い方法について"
  - else
    .credit-card-add_card-wrapper
      .credit-content
        = render "add_card"
  .verification_footer
    = render partial: 'items/shared/verification_footer'

app/views/credit_cards/new.html.haml
.credit-card-wrapper
  .verification_header
    = render partial: 'items/shared/verification_header'
  .credit-content
    .credit-content__item
      %h2.credit-content__item__title
        支払い方法
  -# = form_tag(credit_card_path(@item), method: :post, id: 'charge-form', name: "inputForm", class: "credit-content__products") do
  = form_tag(credit_cards_path, method: :post, id: 'charge-form', name: "inputForm", class: "credit-content__products") do
    .credit-content__product
      .credit-content__product__title
        %label
          カード番号
        %span
          必須
      .credit-content__product--form
        = text_field_tag "number", "", class: "credit__product__card-number", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"
        %ul.credit__producd__card-image
          %li
            = image_tag("visa.svg", size: "49x20")
          %li
            = image_tag("master-card.svg", size: "34x20")
          %li
            = image_tag("saison-card.svg", size: "30x20")
          %li
            = image_tag("jcb.svg", size: "32x20")
          %li
            = image_tag("american_express.svg", size: "21x20")
          %li
            = image_tag("dinersclub.svg", size: "32x20")
          %li
            = image_tag("discover.svg", size: "32x20")
      .credit-content__product__title
        %label
          有効期限
        %span
          必須
      .credit-content__product--form
        %select.select__default#exp_month{name: "exp_month", type: "text"}
          %option{value: ""} --
          %option{value: "1"} 01
          %option{value: "2"} 02
          %option{value: "3"} 03
          %option{value: "4"} 04
          %option{value: "5"} 05
          %option{value: "6"} 06
          %option{value: "7"} 07
          %option{value: "8"} 08
          %option{value: "9"} 09
          %option{value: "10"} 10
          %option{value: "11"} 11
          %option{value: "12"} 12
        %span
          月
        %select.select__default#exp_year{name: "exp_year", type: "text"}
          %option{value: ""} --
          %option{value: "2019"}19
          %option{value: "2020"}20
          %option{value: "2021"}21
          %option{value: "2022"}22
          %option{value: "2023"}23
          %option{value: "2024"}24
          %option{value: "2025"}25
          %option{value: "2026"}26
          %option{value: "2027"}27
          %option{value: "2028"}28
          %option{value: "2029"}29
        %span
          年
      .credit-content__product__title
        %label
          セキュリティーコード
        %span
          必須
      .credit-content__product--form
        = text_field_tag "cvc", "", class: "credit__product__card-number", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      .credit-content__register#card_token
        = submit_tag "登録する", id: "token_submit", class: "top__margin"
  .verification_footer
    = render partial: 'items/shared/verification_footer'