config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
      # 商品編集の際に画像を削除した際、動くメソッドを定義
      delete 'image_delete', defoults: {format: 'json'}
    end
  end
  
  resources :users, only: [:show, :new] do
    collection do
      get :sms
      get :sms_input
      get :completed
    end
    # member do
    #   get "/credit_cards/:id/new" => "credit_card#new"
    # end
  end
  
  resources :purchases, only: [:show] do
    member do
      get :verification_address
      post :create
      post "/credit_cards/:id/create" => "credit_card#create"
      get "pay", to: "purchases#pay"
      post "buy", to: "purchases#buy"
    end
  end
  resources :credit_cards, only: [:index, :new, :create] do
    member do
      # get :new
      # post :create
      post "delete", to: "credit_cards#delete"
    end
  end

  root "items#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require "payjp"
  # before_action :set_item, only: [:show, :verification_address, :create, :purchases_verification, :pay, :buy]
  before_action :set_item
  before_action :set_card
  
  def show
    @address = Address.new
  end
  
  def verification_address
    @address = Address.new
  end
  
  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to pay_purchase_path(@item.id)
    else
      render "verification_address"
    end
  end
  
  def pay
  end

  def buy
    # すでに購入されていないか？
    if @item.buyer.present? 
      redirect_to root_path
    elsif @card.blank?
      # カード情報がなければ、買えないから戻します。
      redirect_to "new_credit_card"
      flash[:alert] = '購入にはクレジットカード登録が必要です'
    else
      # 購入者もいないし、クレジットカードもあるし、決済処理に移行します。
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      # 請求を発行
      Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy',
      )
      # 売り切れなので、itemの情報をアップデートして売り切れにします。
      if @item.update(product_status: 2, buyer_id: current_user.id)
        flash[:notice] = '購入しました。'
        redirect_to root_path
      else
        flash[:alert] = '購入に失敗しました。'
        redirect_to controller: 'purchases' , action: 'show', id: @item.id
      end
     end
    end

  private

  def set_item
    @item = Item.find(params[:id])
    @images = @item.product_images
    @image = @images.first 
  end

  def set_card
    @card = CreditCard.where(user_id: current_user.id).first if CreditCard.where(user_id: current_user.id).present?
  end
    
  def address_params
    params.require(:address).permit(:firstname, :familyname, :firstname_kana, :familyname_kana, :postal_code, :prefectures, :municipality, :address, :building_name).merge(user_id: current_user.id)
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/pay.html.haml
.verification-wrapper
  .verification_header
    = render partial: 'items/shared/verification_header'
  .verification-content
    .verification-content__item
      %h2.verification-content__item__title
        購入内容の確認
      %sectonc.verification-content__item__body
        .verification-content__item__body__caption
          .verification-content__item__body__caption--center
            .verification-content__item__image
              = image_tag(@image.image, size: "80x80")
            .verification-content__item__detail
              %p.verification-content__item__detail__name
                = @item.product_name
              %p.verification-content__item__detail__price
                %span
                  ¥
                  = number_to_currency(@item.price, precision: 0)
                %span
                  (税込) 送料込み
      %section.verification-content__item--payment
        .verification-content__item--payment-body
          .verification-form
            %ul.verification-form__content
              %li.verification-form__content__list
                .verification-form__content__list__title
                  支払い金額
                .verification-form__content__list__price
                  %span
                    ¥
                    = number_to_currency(@item.price, precision: 0)
            %section.verification-form__button
              = form_tag(buy_purchase_path, method: :post) do
                %button 購入する
  .verification_footer
    = render partial: 'items/shared/verification_footer'

app/views/purchases/purchases_verification.html.haml
.verification-wrapper
  .verification_header
    = render partial: 'items/shared/verification_header'
  .verification-content
    .verification-content__item
      %h2.verification-content__item__title
        購入内容の確認
      %sectonc.verification-content__item__body
        .verification-content__item__body__caption
          .verification-content__item__body__caption--center
            .verification-content__item__image
              = image_tag(@image.image, size: "80x80")
            .verification-content__item__detail
              %p.verification-content__item__detail__name
                = @item.product_name
              %p.verification-content__item__detail__price
                %span
                  ¥
                  = number_to_currency(@item.price, precision: 0)     # number_to_currencyはメソッド名です。unitは通貨単位を指定してます。(デフォルトは$です) precisionは少数以下の桁の指定です。(今回は小数点以下は切り捨てたいので0です)  追記 unitはエンマークの表示がうまく行かなかったので消しました。
                %span
                  (税込) 送料込み
      %section.verification-content__item--payment
        .verification-content__item--payment-body
          %form.verification-form
            %ul.verification-form__content
              %li.verification-form__content__list
                .verification-form__content__list__title
                  支払い金額
                .verification-form__content__list__price
                  %span
                    ¥
                    = number_to_currency(@item.price, precision: 0)
            %section.verification-form--payment
              .verification-form--payment__body
                %h3
                  支払い方法
                = link_to credit_card_path(@item) do
                  %i.fas.fa-plus-circle
                  %span
                    登録してください
  .verification_footer
    = render partial: 'items/shared/verification_footer'

app/views/purchases/show.html.haml
.verification-wrapper
  = render "layouts/flash_messages"
  .verification_header
    = render partial: 'items/shared/verification_header'
    .verification-content
      .verification-content__item
        %h2.verification-content__item__title
          購入内容の確認
        %sectonc.verification-content__item__body
          .verification-content__item__body__caption
            .verification-content__item__body__caption--center
              .verification-content__item__image
                = image_tag(@image.image, size: "80x80")
              .verification-content__item__detail
                %p.verification-content__item__detail__name
                  = @item.product_name
                %p.verification-content__item__detail__price
                  %span
                    ¥
                    = number_to_currency(@item.price, precision: 0)
                  %span
                    (税込) 送料込み
        %section.verification-content__item--payment
          .verification-content__item--payment-body
            .verification-form
              %ul.verification-form__content
                %li.verification-form__content__list
                  .verification-form__content__list__title
                    支払い金額
                  .verification-form__content__list__price
                    %span
                      ¥
                      = number_to_currency(@item.price, precision: 0)
              %section.verification-form__add
                - if @card.blank?
                  .verification-form__add__body
                    = link_to user_path(current_user) do
                      %i.fas.fa-plus-circle
                      %span
                        クレジットカードを登録してください
              %section.verification-form__address
                - if @card.present?
                  .verification-form__address__body
                    %h3
                      配送先
                    = link_to verification_address_purchase_path do
                      %i.fas.fa-plus-circle
                      %span
                        登録してください
    .verification_footer
      = render partial: 'items/shared/verification_footer'

app/views/purchases/verification_address.html.haml
.verification-address-wrapper
  .verification_header
    = render partial: 'items/shared/verification_header'
  .verification-address-content
    .verification-address-content__item
      %h2.verification-address-content__item__title
        発送元・お届け先住所入力
  = form_for @address, url: purchase_path do |f|
    - if @address.errors.any?
      = render 'layouts/error_messages', model: f.object
    .verification-address-content__product
      .verification-address-content__product--title
        %label
          お名前
        %span
          必須
      .verification-address-content__product--form
        = f.text_field :firstname, class:'verification-address__product--last-name', placeholder: '例) 山田'
        %br
        = f.text_field :familyname, class:'verification-address__product--first-name', placeholder: '例) 彩'
      .verification-address-content__product--title
        %label
          お名前カナ
        %span
          必須
      .verification-address-content__product--form
        = f.text_field :firstname_kana, class:'verification-address__product--last-name', placeholder: '例) ヤマダ'
        %br
        = f.text_field :familyname_kana, class:'verification-address__product--first-name', placeholder: '例) アヤ'
      .verification-address-content__product--title
        %label
          郵便番号
        %span
          必須
      .verification-address-content__product--form
        = f.text_field :postal_code, class:'verification-address__product--last-name', placeholder: '例) 123-4567'
      .verification-address-content__product--title
        %label
          都道府県
        %span
          必須
      .verification-address-content__product--form
        = f.select :prefectures,[["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県", "千葉県"], ["東京都", "東京都"], ["神奈川県", "神奈川県"], ["新潟県", "新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県", "山梨県"], ["長野県", "長野県"], ["岐阜県", "岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["兵庫県", "兵庫県"], ["和歌山県", "和歌山県"], ["奈良県", "奈良県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"],["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"], ["未定", "未定"]]
      .verification-address-content__product--title
        %label
          市区町村
        %span
          必須
      .verification-address-content__product--form
        = f.text_field :municipality, class:'verification-address__product--last-name', placeholder: '例) 横浜市緑区'
      .verification-address-content__product--title
        %label
          番地
        %span
          必須
      .verification-address-content__product--form
        = f.text_field :address, class:'verification-address__product--last-name', placeholder: '例) 青山1-1-1'
      .verification-address-content__product--title
        %label
          建物名
        %span.any
          任意
      .verification-address-content__product--form
        = f.text_field :building_name, class:'verification-address__product--last-name', placeholder: '例) 柳ビル103'
      .verification-address-content__register
        = f.submit '登録する', class: 'button-address'
  .verification_footer
    = render partial: 'items/shared/verification_footer'