config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
      # 商品編集の際に画像を削除した際、動くメソッドを定義
      delete 'image_delete', defoults: {format: 'json'}
    end
  end
  
  resources :users, only: [:show, :new] do
    collection do
      get :sms
      get :sms_input
      get :completed
    end
    # member do
    #   get "/credit_cards/:id/new" => "credit_card#new"
    # end
  end
  
  resources :purchases, only: [:show] do
    member do
      get :verification_address
      post :create
      post "/credit_cards/:id/create" => "credit_card#create"
      get "pay", to: "purchases#pay"
      post "buy", to: "purchases#buy"
    end
  end
  resources :credit_cards, only: [:index, :new, :create] do
    member do
      # get :new
      # post :create
      post "delete", to: "credit_cards#delete"
    end
  end

  root "items#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User", optional: true
  # dependent: :destroyオプション → 親レコードを削除した際、子レコードも同時に削除する。
  has_many :product_images, dependent: :destroy
  # accepts_nested_attributes_forメソッドより、親モデルを通じてネストしたモデルの関連レコードの登録・更新を可能にする
  # allow_destroy: true → 親レコードに関連した子レコードを削除することができる。
  accepts_nested_attributes_for :product_images, allow_destroy: true
  has_many :likes
  has_many :comments
  has_one :purchase_history
  has_one :sell_history
  belongs_to :category, optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # バリデーション
  validates :product_name, :product_information, :product_status, :price, :product_condition, :shipping_charge, :days_of_ship, :prefecture_id, presence: true
  validates :product_name, length: { maximum: 40 }
  validates :product_information, length: { maximum: 1000 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates_associated :product_images
  validate :product_images_number
  validates :category_id, presence: true

  private
  def product_images_number
    if product_images.size < 1 
      errors.add(:product_image, "product_images are blank")
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # ログイン中のユーザーのみ実行可能にする（トップページと商品詳細ページは除く）
  before_action :authenticate_user!, {only: [:new, :create, :edit, :destroy]}
  before_action :set_item, only:['edit', 'update']

  def index
    @items = Item.limit(3).order('id DESC')
  end

  def new
    @item = Item.new
    # カテゴリーの親を取得
    @category = Category.where(ancestry: nil)
    # @itemにproduct_imagesの情報を入れることのできるインスタンスを生成
    @item.product_images.build
  end
  
  def create
    @item = Item.new(item_params)
    respond_to do |format|
      # バリデーションチェックが通ればフォーム記載内容をデータベースに保存する
      # また、バリデーションチェックした際のエラーメッセージをjson形式にてnew_item.jsへ返す
      if @item.valid? 
        @item.save
        format.html { redirect_to root_path }
        format.json { render json: @item.errors.messages }
      else
        format.json { render json: @item.errors.messages }
      end
    end
  end
  
  def get_category_children
    @children = Category.find(params[:parent_category_id]).children
    respond_to do |format|
      format.html
      format.json { render json: @children }
    end
  end

  def get_category_grandchildren
    @grandchildren = Category.find(params[:child_category_id]).children
    respond_to do |format|
      format.html
      format.json { render json: @grandchildren }
    end
  end

  def show
    @item = Item.find(params[:id])
    @seller = User.find(@item.seller_id)
    @images = @item.product_images
    @image = @images.first
    @prefecture = Prefecture.find(@item.prefecture_id)
    @condition = @item.product_condition
    @days_of_ship = @item.days_of_ship
    @charge = @item.shipping_charge
    @grandchildren = Category.find(@item.category_id)
    @children = @grandchildren.parent
    @parent = @children.parent
  end

  def edit
    @images = @item.product_images
    @parent_category = @item.category.parent.parent.siblings
    @child_category = @item.category.parent.siblings
    @grandchild_category = @item.category.siblings
  end

  def image_delete
    @image = ProductImage.find(params[:product_image_id])
    @image.destroy
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        @item.valid? 
        format.html { redirect_to root_path }
        format.json { render json: @item.errors.messages }
      else
        @item.valid? 
        format.json { render json: @item.errors.messages }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end
  
  private
  def item_params
    params.require(:item).permit(
      :product_name,
      :product_information,
      :product_status,
      :price,
      :product_condition,
      :shipping_charge,
      :prefecture_id,
      :days_of_ship, 
      :brand,
      :size,
      :category_id,
      # attributesを用いてparamsの中にproduct_imagesの情報が入ることを許可
      product_images_attributes: [:id, 
                                 :image,
                                 :item_id],)
      .merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/shared/_item-buy-button.html.haml
-if @item.product_status == 2
  .item-box__buy-button
    = link_to "売り切れました", ""
-elsif not user_signed_in? 
  .item-box__buy-button
    = link_to "購入画面に進む", new_user_session_path
-elsif user_signed_in? && @item.seller_id != current_user.id
  .item-box__buy-button
    = link_to "購入画面に進む", purchase_path(@item.id)

app/views/items/shared/_item-detail-footer.html.haml
%ul.footer__contents
  %li.content
    %h2.content__head FURIMAについて
    %ul
      %li
        = link_to  "＃", class: "content--link" do
          会社概要（運営会社）
      %li
        = link_to  "＃", class: "content--link" do
          プライバシーポリシー
      %li
        = link_to  "＃", class: "content--link" do
          FURIMA利用規約
      %li
        = link_to  "＃", class: "content--link" do
          ポイントに関する特約
  %li.content
    %h2.content__head FURIMAを見る
    %ul
      %li
        = link_to  "＃", class: "content--link" do
          カテゴリー一覧
      %li
        = link_to  "＃", class: "content--link" do
          ブランド一覧
  %li.content
    %h2.content__head ヘルプ＆ガイド
    %ul
      %li
        = link_to  "＃", class: "content--link" do
          FURIMAガイド
      %li
        = link_to  "＃", class: "content--link" do
          FURIMAロゴ利用ガイドライン
      %li
        = link_to  "＃", class: "content--link" do
          お知らせ
.footer__logo
= link_to image_tag("logo-white.png", class: "white-logo", width: "160"), "＃"
%p.footer__logo--small © FURIMA

app/views/items/shared/_item-edit-delete.html.haml
:javascript
  document.addEventListener(
    "DOMContentLoaded", e => {
      let modal_open = document.getElementById("modal-open");
      modal_open.onclick = function () {
        $('#overlay').fadeIn();
        document.getElementById('modal-close').onclick = function () {
          $('#overlay').fadeOut();
        };
        document.getElementById("delete-comformation").onclick = function () {
          document.getElementById("item-delete").click();
        };
      };
    },
    false
  );
-if user_signed_in?
  -if @item.seller_id == current_user.id
    .item-change
      .item-change--button.btn-blue
        = link_to "商品の編集", edit_item_path(@item.id)
      %p.text-center or
      #modal-open.btn-gray  この商品を削除する 
      = link_to "", item_path(@item.id), method: :delete, id: "item-delete"
      #overlay
        #modal-window
          .modal-message-box
            %div.bold 確認
            %div 削除すると二度と復活できません。
            %div 本当に削除しますか？
          #modal-close 
            = link_to "キャンセル" , item_path(@item.id)
          #delete-comformation 
            = link_to "削除する", root_path

app/views/items/shared/_purchase-button.html.haml
%span.purchase-button--text
  出品する
  = link_to image_tag("icon_camera.png", class: "purchase-button--icon"), "＃"

app/views/items/shared/_top_footer.html.haml
.top-app__content
  .top-app__content-inner
    %h2.top-app__content-inner--title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.top-app__content-inner--text
      今すぐ無料ダウンロード!
    .top-app__content-inner--icon
      = link_to image_tag("sozai-02.png")
      = link_to image_tag("sozai-05.png")
.top-footer__information
  %ul.top-footer__information--contents
    %li.top-footer__information--contents-content
      %h2.top-footer__content
        FURIMAについて
      %ul
        %li
          %a{href: '#' } 会社概要(運営会社)
        %li
          %a{href: '#' } プライバシーポリシー
        %li
          %a{href: '#'} FURIMA利用規約
        %li
          %a{href: '#'} ポイントに関する規約
    %li.top-footer__information--contents-content
      %h2.top-footer__content
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            カテゴリー一覧
        %li
          = link_to "#" do
            ブランド一覧
    %li.top-footer__information--contents-content
      %h2.top-footer__content
        ヘルプ&ガイド
      %ul
        %li
          = link_to "#" do
            FURIMAガイド
        %li
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            お知らせ
  .top-footer__logo
    = link_to image_tag("logo-white.png")
    %p
      ©︎ FURIMA
    .body-function__button
      = link_to new_item_path do
        %span.body-function__button-text
          出品する
        = image_tag("icon_camera.png", class: "camera")

app/views/items/shared/_top_header.html.haml
.top-header
  .top-header__inner
    .top-header__inner__main
      %h1.top-header__inner__log
        = link_to image_tag("logo.png", size: "134x36", class: "logo"), root_path
      .top-header__inner__main--search
        %form.top-header__inner__main--search--form
          %input.search-form{name: "", placeholder: "キーワードから探す", type: "text", value: ""}/
          %button.search-button
            %i.fas.fa-search

    .top-header__information
      %ul.top-header--items-left
        %li.top-header--items-left--item-first
          カテゴリー
        %li.top-header--items-left--item-second
          ブランド
      - if user_signed_in?
        %ul.top-header--items-right
          - if current_page?(root_url)
            %li.top-header--items-right--login
              = link_to "ログアウト", destroy_user_session_path, method: :delete
            %li.top-header--items-right--login
              = link_to "/users/current_user" do
                マイページ
          - else
            %li.top-header--items-right--login
              = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        %ul.top-header--items-right
          %li.top-header--items-right--login
            = link_to "/users/sign_in" do
              ログイン
          %li.top-header--items-right--new
            = link_to "/users/new" do
              新規会員登録

app/views/items/shared/_verification_footer.html.haml
.verification-footer__information
  %ul.verification-footer__information--lists
    %li.verification-footer__information--list
      = link_to "プライバシーポリシー"
    %li.verification-footer__information--list
      = link_to "フリマ利用規約"
    %li.verification-footer__information--list
      = link_to "特定商取引に関する表記"
  .verification-footer__information__logo
    = link_to image_tag("logo-white.png"), root_path
    %p
      ©︎ FURIMA

app/views/items/shared/_verification_header.html.haml
.verification-header
  .verification-header__icon
    = image_tag("logo.png")