config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: {format: 'json'}
      get 'get_category_grandchildren', defaults: {format: 'json'}
      # 商品編集の際に画像を削除した際、動くメソッドを定義
      delete 'image_delete', defoults: {format: 'json'}
    end
  end
  
  resources :users, only: [:show, :new] do
    collection do
      get :sms
      get :sms_input
      get :completed
    end
    # member do
    #   get "/credit_cards/:id/new" => "credit_card#new"
    # end
  end
  
  resources :purchases, only: [:show] do
    member do
      get :verification_address
      post :create
      post "/credit_cards/:id/create" => "credit_card#create"
      get "pay", to: "purchases#pay"
      post "buy", to: "purchases#buy"
    end
  end
  resources :credit_cards, only: [:index, :new, :create] do
    member do
      # get :new
      # post :create
      post "delete", to: "credit_cards#delete"
    end
  end

  root "items#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User", optional: true
  # dependent: :destroyオプション → 親レコードを削除した際、子レコードも同時に削除する。
  has_many :product_images, dependent: :destroy
  # accepts_nested_attributes_forメソッドより、親モデルを通じてネストしたモデルの関連レコードの登録・更新を可能にする
  # allow_destroy: true → 親レコードに関連した子レコードを削除することができる。
  accepts_nested_attributes_for :product_images, allow_destroy: true
  has_many :likes
  has_many :comments
  has_one :purchase_history
  has_one :sell_history
  belongs_to :category, optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # バリデーション
  validates :product_name, :product_information, :product_status, :price, :product_condition, :shipping_charge, :days_of_ship, :prefecture_id, presence: true
  validates :product_name, length: { maximum: 40 }
  validates :product_information, length: { maximum: 1000 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates_associated :product_images
  validate :product_images_number
  validates :category_id, presence: true

  private
  def product_images_number
    if product_images.size < 1 
      errors.add(:product_image, "product_images are blank")
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # ログイン中のユーザーのみ実行可能にする（トップページと商品詳細ページは除く）
  before_action :authenticate_user!, {only: [:new, :create, :edit, :destroy]}
  before_action :set_item, only:['edit', 'update']

  def index
    @items = Item.limit(3).order('id DESC')
  end

  def new
    @item = Item.new
    # カテゴリーの親を取得
    @category = Category.where(ancestry: nil)
    # @itemにproduct_imagesの情報を入れることのできるインスタンスを生成
    @item.product_images.build
  end
  
  def create
    @item = Item.new(item_params)
    respond_to do |format|
      # バリデーションチェックが通ればフォーム記載内容をデータベースに保存する
      # また、バリデーションチェックした際のエラーメッセージをjson形式にてnew_item.jsへ返す
      if @item.valid? 
        @item.save
        format.html { redirect_to root_path }
        format.json { render json: @item.errors.messages }
      else
        format.json { render json: @item.errors.messages }
      end
    end
  end
  
  def get_category_children
    @children = Category.find(params[:parent_category_id]).children
    respond_to do |format|
      format.html
      format.json { render json: @children }
    end
  end

  def get_category_grandchildren
    @grandchildren = Category.find(params[:child_category_id]).children
    respond_to do |format|
      format.html
      format.json { render json: @grandchildren }
    end
  end

  def show
    @item = Item.find(params[:id])
    @seller = User.find(@item.seller_id)
    @images = @item.product_images
    @image = @images.first
    @prefecture = Prefecture.find(@item.prefecture_id)
    @condition = @item.product_condition
    @days_of_ship = @item.days_of_ship
    @charge = @item.shipping_charge
    @grandchildren = Category.find(@item.category_id)
    @children = @grandchildren.parent
    @parent = @children.parent
  end

  def edit
    @images = @item.product_images
    @parent_category = @item.category.parent.parent.siblings
    @child_category = @item.category.parent.siblings
    @grandchild_category = @item.category.siblings
  end

  def image_delete
    @image = ProductImage.find(params[:product_image_id])
    @image.destroy
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        @item.valid? 
        format.html { redirect_to root_path }
        format.json { render json: @item.errors.messages }
      else
        @item.valid? 
        format.json { render json: @item.errors.messages }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end
  
  private
  def item_params
    params.require(:item).permit(
      :product_name,
      :product_information,
      :product_status,
      :price,
      :product_condition,
      :shipping_charge,
      :prefecture_id,
      :days_of_ship, 
      :brand,
      :size,
      :category_id,
      # attributesを用いてparamsの中にproduct_imagesの情報が入ることを許可
      product_images_attributes: [:id, 
                                 :image,
                                 :item_id],)
      .merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
.exhibition-wrapper
  .exhibition-header
    .exhibition-header__icon
      = image_tag("logo.png")
  = form_for @item, html: {name: 'new_item', id: 'item_form'} do |f|
    .exhibition-contents
      .item-edit-title
        商品情報の編集
      .exhibition-content__caption
        .exhibition-content__caption--title
          %label
            出品画像
          %span  
            必須
        %p.exhibition-content__caption--text
          最大５枚までアップロードできます
        .exhibition-content__caption--image--box
          - @item.product_images.each_with_index do |image, i|
            .item-image{ id: "image-#{i}", "data-image_id": "#{i}", "data-product_image_id": image.id }
              .item-image__content
                .item-image__content--icon
                  = image_tag image.image, size: "113x80", class: 'item-image__content--icon'
              .item-image__operation
                .item-image__operation--delete
                  削除
          .exhibition-content__caption--image
            = icon('fas', 'camera')
          .input_box                  
            = f.fields_for :product_images do |s|
              = s.file_field :image, class: 'exhibition-content__caption--image--default'
            - image_number = @item.product_images.length
            %input.exhibition-content__caption--image--default{type: 'file', name: "item[product_images_attributes][#{image_number}][image]", id: "item_product_images_attributes_#{image_number}_image"}
            -# ここにプレビューのコードを挿入
        -# ここにエラーメッセージを挿入
      .exhibition-content__product
        .exhibition-content__product--name
          .exhibition-content__product--name--title
            %label
              商品名
            %span
              必須
          .exhibition-content__product--name--form
            = f.text_field :product_name, placeholder: "40字まで", maxlength: "40", class: "exhibition__product--name"
        -# ここにエラーメッセージを挿入
        .exhibition-content__product--description
          .exhibition-content__product--description--title
            %label
              商品の説明
            %span
              必須
          .exhibition-content__product--description--form
            = f.text_area :product_information, class: "exhibition--description--text", rows: "8", placeholder: "商品の説明 (必須 1,000文字以内)\n (色、素材、重さ、定価、注意点など)\n\n例) 2010年頃に1万円でこうにゅうしたジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
            .exhibition--description--text--counter
              %span.counter 0/1000
            .product_information_alert
          -# ここにエラーメッセージを挿入
      .exhibition-content__details
        %p.exhibition-content__details--heading
          商品の詳細
        .exhibition-content__details--category
          .exhibition-content__details--category--title
            %label
              カテゴリー
            %span
              必須
          -# 下はancestoryのGemを導入したあと、変更予定
          = f.collection_select :category_id, @parent_category, :id, :name, { selected: @item.category.parent.parent[:id] }, class: "exhibition-content__details--category--form", id: "parent-category"
          = f.collection_select :category_id, @child_category, :id, :name, { selected: @item.category.parent[:id]}, class: "exhibition-content__details--category--form", id: "child-category"
          = f.collection_select :category_id, @grandchild_category, :id, :name, { selected: @item.category[:id] }, class: "exhibition-content__details--category--form", id: "grandchild-category"
        .exhibition-content__details--brand
          .exhibition-content__details--brand--title
            %label
              ブランド
            %span.brand
              任意
          = f.text_field :brand, placeholder: "例) シャネル", class: "exhibition-content__details--brand--form"
        .exhibition-content__details--Status
          .exhibition-content__details--Status--title
            %label
              商品の状態
            %span
              必須
          .exhibition-content__details--Status--form
            = f.select :product_condition, [["新品、未使用", "0"], ["未使用に近い", "1"], ["目立った傷や汚れなし", "2"], ["やや傷や汚れあり", "3"], ["傷や汚れあり", "4"], ["全体的に状態が悪い", "5"]], {prompt: "選択してください"}, class: "product_condition--form"
          -# ここにエラーメッセージを挿入
      .exhibition-content__delivery
        %p.exhibition-content__delivery--heading
          配送について
          = link_to "#" do
            %i.far.fa-question-circle
        .exbition-content__delivery--burden
          .exhibition-content__delivery--burden--title
            %label
              配送料の負担
            %span
              必須
          .exhibition-content__delivery--burden--form
            = f.select :shipping_charge, [["送料込み（出品者負担）", "0"], ["着払い（購入者負担）", "1"]], {prompt: "選択してください"}, class: "shipping_charge--form"
          -# ここにエラーメッセージを挿入
        .exbition-content__delivery--area
          .exhibition-content__delivery--area--title
            %label
              発送元の地域
            %span
              必須
          .exhibition-content__delivery--area--form
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, class: "shipping_area--form"
          -# ここにエラーメッセージを挿入
        .exhibition-content__delivery--days
          .exhibition-content__delivery--days--title
            %label
              発送までの日数
            %span
              必須
          .exhibition-content__delivery--days--form
            = f.select :days_of_ship, [["1~2日で発送", "0"], ["2~3日で発送", "1"], ["4~7日で発送", "2"]], {prompt: "選択してください"}, class: "days_of_ship--form"
          -# ここにエラーメッセージを挿入
      .exhibition-content__price
        %p.exhibition-content__price--heading
          価格 (￥300~9,999,999)
          = link_to "#" do
            %i.far.fa-question-circle
        .exhibition-content__price--selling
          .exhibition-content__price--selling--title
            %label
              販売価格
            %span.selling-span
              必須
            .exhibition-content__price--selling--unity
              %span
                ¥
              = f.number_field :price, class: "price--form", max: 9999999, min: 300, placeholder: 0
            -# ここにエラーメッセージを挿入
          .exhibition-content__price--fee
            .exhibition-content__price--fee-label
              販売手数料 (10%)
            %span.exhibition-content__price--fee-value
              ー
          .exhibition-content__price--revenue
            .exhibition-content__price--revenue-label
              販売利益
            %span.exhibion-content__price--revenue-value
              ー
          .exhibition-content__price--listing
            .edit_button
              変更する
          .exhibition-content__price--return
            = link_to root_path do
              %button{type: "button"}
                もどる
          %p.exhibition-content__price--caution
            禁止されている
            = link_to "行為" 
            および
            = link_to "出品物"
            を必ずご確認ください。
            = link_to "偽ブランド品"
            や
            = link_to "盗品物"
            などの販売は犯罪であり、法律により処罰される可能性があります。 また、 出品をもちまして
            = link_to "加盟店規約"
            に同意したことになります。
  .exhibition-footer__information
    %ul.exhibition-footer__information--lists
      %li.exhibition-footer__information--list
        = link_to "プライバシーポリシー"
      %li.exhibition-footer__information--list
        = link_to "フリマ利用規約"
      %li.exhibition-footer__information--list
        = link_to "特定商取引に関する表記"
    .exhibition-footer__information__logo
      = link_to image_tag("logo-white.png")
      %p
        ©︎ FURIMA

app/views/items/index.html.haml
.top_header
  = render partial: 'items/shared/top_header'
.top-main
  %section.top-main__visual
    .top-content
      %h2.top-content__title
        %br
        人生を変えるフリマアプリ
      %p.top-content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .top-content__button
        = link_to image_tag("sozai-02.png")
        = link_to image_tag("sozai-05.png")
  - if user_signed_in?
    %section.top-main__pickupcategory
      %h2.top-main__pickupcategory-title
        ピックアップカテゴリー
      .top-main__pickupcategory--box
        .top-main__pickupcategory--box-title
          = link_to "#" do
            %h3.title
              新規投稿商品
        .top-main__pickupcategory--lists
          - @items.each do |item|
            .top-main__pickupcategory--lists-list
              %figure.top-main__pickupcategory--lists-list--image
                = link_to item_path(item.id) do
                  = image_tag item.product_images[0].image
                -if item.buyer_id.present?
                  .sold-out 
                  .sold-out-font SOLD
              .top-main__pickupcategory--lists-list--text
                %h3.name
                  = item.product_name
                .details
                  %ul
                    %li 
                      = item.price
                    %li
                      %i.fa.fa-star.likeIcon
                        0
                  %p
                    (税込)
    -# %section.top-main__pickupcategory
    -#   %h2.top-main__pickupcategory-title
    -#     ピックアップブランド
    -#   .top-main__pickupcategory--box
    -#     .top-main__pickupcategory--box-title
    -#       = link_to "#" do
    -#         %h3.title
    -#           アーカイバ
    -#     .top-main__pickupcategory--lists
    -#       .top-main__pickupcategory--lists-list
    -#         %figure.top-main__pickupcategory--lists-list--image
    -#           = link_to image_tag("sozai-01.png")
    -#         .top-main__pickupcategory--lists-list--text
    -#           %h3.name
    -#             ネズミ達
    -#           .details
    -#             %ul
    -#               %li 
    -#                 1000円
    -#               %li
    -#                 %i.fa.fa-star.likeIcon
    -#                   0
    -#             %p
    -#               (税込)
    -#       .top-main__pickupcategory--lists-list
    -#         %figure.top-main__pickupcategory--lists-list--image
    -#           = link_to image_tag("sozai-01.png")
    -#         .top-main__pickupcategory--lists-list--text
    -#           %h3.name
    -#             ネズミ達
    -#           .details
    -#             %ul
    -#               %li 
    -#                 1000円
    -#               %li
    -#                 %i.fa.fa-star.likeIcon
    -#                   0
    -#             %p
    -#               (税込)
    -#       .top-main__pickupcategory--lists-list
    -#         %figure.top-main__pickupcategory--lists-list--image
    -#           = link_to image_tag("sozai-01.png")
    -#         .top-main__pickupcategory--lists-list--text
    -#           %h3.name
    -#             ネズミ達
    -#           .details
    -#             %ul
    -#               %li 
    -#                 1000円
    -#               %li
    -#                 %i.fa.fa-star.likeIcon
    -#                   0
    -#             %p
    -#               (税込)
    .top_app__content
      = render partial: 'items/shared/top_footer'
  - else
    %section.top-main__introduction
      %h2.top-main__introduction-subtitle
        FURIMAが選ばれる3つの理由
      %ul.top-main__lists
        %li.top-main__lists-list--first
          .top-list__picture
            %span.top-number
              1
            = image_tag "pict-reason-01.jpg"
          %h3.top-list__text
            %span 3分
            ですぐに出品
          %p.top-list__description
            スマホで入力するだけで簡単に出品できる!
        %li.top-main__lists-list--second
          .top-list__picture
            %span.top-number
              2
            = image_tag "pict-reason-02.jpg"
          %h3.top-list__text
            %span シンプル
            で使いやすい
          %p.top-list__description
            めんどくさい入力は必要なく、検索も購入もスムーズ!
        %li.top-main__lists-list--last
          .top-list__picture
            %span.top-number
              3
            = image_tag "pict-reason-03.jpg"
          %h3.top-list__text
            手数料
            %span 業界最安
          %p.top-list__description
            最大3%でお得に出品&購入!
    %section.top-main__introduction-link
      .top-main__introduction-content
        %h2.top-main__introduction-title
          会員数日本一位
        %p.top-main__introduction-text
          FURIMAは、フリマアプリで最も人気。
          %br
          出品・購入回数も業界最多です!
          %br
          ほしかったあの商品に出会えるかもしれません。
        .top-main__introduction-button
          = link_to image_tag("sozai-02.png")
          = link_to image_tag("sozai-05.png")
    %section.top-main__introduction-features
      %h2.top-main__introduction-title
        FURIMAの特徴
      .top-main__introduction-items
        %section.top-main__item
          %figure.top-main__item-image
            = image_tag "icon-01.png"
          %h3.top-main__item-subtitle
            簡単に売り買いできる
          %p.top-main__item-text
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能!
        %section.top-main__item
          %figure.top-main__item-image
            = image_tag "icon-03.png"
          %h3.top-main__item-subtitle
            売上金は即日振込に対応
          %p.top-main__item-text
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        %section.top-main__item
          %figure.top-main__item-image
            = image_tag "icon-04.png"
          %h3.top-main__item-subtitle
            様々な支払いに対応
          %p.top-main__item-text
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    %section.top-main__pickupcategory
      %h2.top-main__pickupcategory-title
        ピックアップカテゴリー
      .top-main__pickupcategory--box
        .top-main__pickupcategory--box-title
          = link_to "#" do
            %h3.title
              新規投稿商品
        .top-main__pickupcategory--lists
          - @items.each do |item|
            .top-main__pickupcategory--lists-list
              %figure.top-main__pickupcategory--lists-list--image
                = link_to item_path(item.id) do
                  = image_tag item.product_images[0].image
                -if item.buyer_id.present?
                  .sold-out 
                  .sold-out-font SOLD
              .top-main__pickupcategory--lists-list--text
                %h3.name
                  = item.product_name
                .details
                  %ul
                    %li 
                      = item.price
                    %li
                      %i.fa.fa-star.likeIcon
                        0
                  %p
                    (税込)
      -# %section.top-main__pickupcategory
      -#   %h2.top-main__pickupcategory-title
      -#     ピックアップブランド
      -#   .top-main__pickupcategory--box
      -#     .top-main__pickupcategory--box-title
      -#       = link_to "#" do
      -#         %h3.title
      -#           アーカイバ
      -#     .top-main__pickupcategory--lists
      -#       .top-main__pickupcategory--lists-list
      -#         %figure.top-main__pickupcategory--lists-list--image
      -#           = link_to image_tag("sozai-01.png")
      -#         .top-main__pickupcategory--lists-list--text
      -#           %h3.name
      -#             ネズミ達
      -#           .details
      -#             %ul
      -#               %li 
      -#                 1000円
      -#               %li
      -#                 %i.fa.fa-star.likeIcon
      -#                   0
      -#             %p
      -#               (税込)
      -#       .top-main__pickupcategory--lists-list
      -#         %figure.top-main__pickupcategory--lists-list--image
      -#           = link_to image_tag("sozai-01.png")
      -#         .top-main__pickupcategory--lists-list--text
      -#           %h3.name
      -#             ネズミ達
      -#           .details
      -#             %ul
      -#               %li 
      -#                 1000円
      -#               %li
      -#                 %i.fa.fa-star.likeIcon
      -#                   0
      -#             %p
      -#               (税込)
      -#       .top-main__pickupcategory--lists-list
      -#         %figure.top-main__pickupcategory--lists-list--image
      -#           = link_to image_tag("sozai-01.png")
      -#         .top-main__pickupcategory--lists-list--text
      -#           %h3.name
      -#             ネズミ達
      -#           .details
      -#             %ul
      -#               %li 
      -#                 1000円
      -#               %li
      -#                 %i.fa.fa-star.likeIcon
      -#                   0
      -#             %p
      -#               (税込)
      .top_app__content
        = render partial: 'items/shared/top_footer'

app/views/items/new.html.haml
.exhibition-wrapper
  .exhibition-header
    .exhibition-header__icon
      = image_tag("logo.png")
  = form_for @item, html: {name: 'new_item'} do |f|
    .exhibition-contents
      .exhibition-content__caption
        .exhibition-content__caption--title
          %label
            出品画像
          %span  
            必須
        %p.exhibition-content__caption--text
          最大５枚までアップロードできます
        .exhibition-content__caption--image--box
          .exhibition-content__caption--image
            = icon('fas', 'camera')
          = f.fields_for :product_images do |s|
            .input_box
              = s.file_field :image, class: 'exhibition-content__caption--image--default'
            -# ここにプレビューのコードを挿入
        -# ここにエラーメッセージを挿入
      .exhibition-content__product
        .exhibition-content__product--name
          .exhibition-content__product--name--title
            %label
              商品名
            %span
              必須
          .exhibition-content__product--name--form
            = f.text_field :product_name, placeholder: "40字まで", maxlength: "40", class: "exhibition__product--name"
        -# ここにエラーメッセージを挿入
        .exhibition-content__product--description
          .exhibition-content__product--description--title
            %label
              商品の説明
            %span
              必須
          .exhibition-content__product--description--form
            = f.text_area :product_information, class: "exhibition--description--text", rows: "8", placeholder: "商品の説明 (必須 1,000文字以内)\n (色、素材、重さ、定価、注意点など)\n\n例) 2010年頃に1万円でこうにゅうしたジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
            .exhibition--description--text--counter
              %span.counter 0/1000
            .product_information_alert
          -# ここにエラーメッセージを挿入
      .exhibition-content__details
        %p.exhibition-content__details--heading
          商品の詳細
        .exhibition-content__details--category
          .exhibition-content__details--category--title
            %label
              カテゴリー
            %span
              必須
          -# 下はancestoryのGemを導入したあと、変更予定
          = f.collection_select :category_id, @category, :id, :name, {prompt: "選択してください"}, class: "exhibition-content__details--category--form", id: "parent-category"
        .exhibition-content__details--brand
          .exhibition-content__details--brand--title
            %label
              ブランド
            %span.brand
              任意
          = f.text_field :brand, placeholder: "例) シャネル", class: "exhibition-content__details--brand--form"
        .exhibition-content__details--Status
          .exhibition-content__details--Status--title
            %label
              商品の状態
            %span
              必須
          .exhibition-content__details--Status--form
            = f.select :product_condition, [["新品、未使用", "0"], ["未使用に近い", "1"], ["目立った傷や汚れなし", "2"], ["やや傷や汚れあり", "3"], ["傷や汚れあり", "4"], ["全体的に状態が悪い", "5"]], {prompt: "選択してください"}, class: "product_condition--form"
          -# ここにエラーメッセージを挿入
      .exhibition-content__delivery
        %p.exhibition-content__delivery--heading
          配送について
          = link_to "#" do
            %i.far.fa-question-circle
        .exbition-content__delivery--burden
          .exhibition-content__delivery--burden--title
            %label
              配送料の負担
            %span
              必須
          .exhibition-content__delivery--burden--form
            = f.select :shipping_charge, [["送料込み（出品者負担）", "0"], ["着払い（購入者負担）", "1"]], {prompt: "選択してください"}, class: "shipping_charge--form"
          -# ここにエラーメッセージを挿入
        .exbition-content__delivery--area
          .exhibition-content__delivery--area--title
            %label
              発送元の地域
            %span
              必須
          .exhibition-content__delivery--area--form
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, class: "shipping_area--form"
          -# ここにエラーメッセージを挿入
        .exhibition-content__delivery--days
          .exhibition-content__delivery--days--title
            %label
              発送までの日数
            %span
              必須
          .exhibition-content__delivery--days--form
            = f.select :days_of_ship, [["1~2日で発送", "0"], ["2~3日で発送", "1"], ["4~7日で発送", "2"]], {prompt: "選択してください"}, class: "days_of_ship--form"
          -# ここにエラーメッセージを挿入
      .exhibition-content__price
        %p.exhibition-content__price--heading
          価格 (￥300~9,999,999)
          = link_to "#" do
            %i.far.fa-question-circle
        .exhibition-content__price--selling
          .exhibition-content__price--selling--title
            %label
              販売価格
            %span.selling-span
              必須
            .exhibition-content__price--selling--unity
              %span
                ¥
              = f.number_field :price, class: "price--form", max: 9999999, min: 300, placeholder: 0
            -# ここにエラーメッセージを挿入
          .exhibition-content__price--fee
            .exhibition-content__price--fee-label
              販売手数料 (10%)
            %span.exhibition-content__price--fee-value
              ー
          .exhibition-content__price--revenue
            .exhibition-content__price--revenue-label
              販売利益
            %span.exhibion-content__price--revenue-value
              ー
          .exhibition-content__price--listing
            .button
              出品する
          .exhibition-content__price--return
            = link_to root_path do
              %button{type: "button"}
                もどる
          %p.exhibition-content__price--caution
            禁止されている
            = link_to "行為" 
            および
            = link_to "出品物"
            を必ずご確認ください。
            = link_to "偽ブランド品"
            や
            = link_to "盗品物"
            などの販売は犯罪であり、法律により処罰される可能性があります。 また、 出品をもちまして
            = link_to "加盟店規約"
            に同意したことになります。
  .exhibition-footer__information
    %ul.exhibition-footer__information--lists
      %li.exhibition-footer__information--list
        = link_to "プライバシーポリシー"
      %li.exhibition-footer__information--list
        = link_to "フリマ利用規約"
      %li.exhibition-footer__information--list
        = link_to "特定商取引に関する表記"
    .exhibition-footer__information__logo
      = link_to image_tag("logo-white.png")
      %p
        ©︎ FURIMA

app/views/items/verification.html.haml
.verification-wrapper
  .verification_header
    = render partial: 'items/shared/verification_header'
  .verification-content
    .verification-content__item
      %h2.verification-content__item__title
        購入内容の確認
      %sectonc.verification-content__item__body
        .verification-content__item__body__caption
          .verification-content__item__body__caption--center
            .verification-content__item__image
              = image_tag("sozai-09.png")
            .verification-content__item__detail
              %p.verification-content__item__detail__name
                星
              %p.verification-content__item__detail__price
                %span
                  ￥1,000
                %span
                  (税込) 送料込み
      %section.verification-content__item--payment
        .verification-content__item--payment-body
          %form.verification-form
            %ul.verification-form__content
              %li.verification-form__content__list
                .verification-form__content__list__title
                  支払い金額
                .verification-form__content__list__price
                  %span
                    ￥1,000
            %section.verification-form--payment
              .verification-form--payment__body
                %h3
                  支払い方法
                = link_to credit_items_path do
                  %i.fas.fa-plus-circle
                  %span
                    登録してください
            %section.verification-form__address
              .verification-form__address__body
                %h3
                  配送先
                = link_to verification_address_items_path do
                  %i.fas.fa-plus-circle
                  %span
                    登録してください
            %section.verification-form__button
              = link_to "#" do
                %button{type: "button"}
                  購入する
  .verification_footer
    = render partial: 'items/shared/verification_footer'